apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-local
spec:
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem  
