apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-local
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: local
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mysql/data
  
