apiVersion: v1
kind: PresistentVolumeClaim
metadata:
  name: mysql-pvc
  spec:
    storageClassName: standard
    resources:
      requests:
        storage: 4Gi
     accessModes:
        - ReadWriteOnce
        
